### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by GaelB505** [jarmeister99/otter#5]
countdown from 5
00500093
00008663
fff08093
ff9ff06f
0000006f (infinite loop) or 00708093 (add 7)

0: li x1 5
4: beqz x1, 10 (done)
8: addi x1, x1, -1
c: j 4 (loop)
10: j 10 (done)

**Comment by jarmeister99** [comment]
0: 00500093   - li x1 5
4: 00008663   - beqz x1, 10 (done)
8: fff08093     - addi x1, x1, -1
c: ff9ff06f       - j 4 (loop)
10: 0000006f - j 10 (done)

**Comment by jarmeister99** [comment]
Fixed
