### ISSUE TITLE
Countdown V2

### ISSUE THREAD

**Issue by GaelB505** [jarmeister99/otter#6]
li x1, 15
li x2, 3
loop: addi x2, x2, 3
mv x3, x2
BEQ x1, x2, done
j loop
done: mv x2, x0
d: j d

00F00093
00300113
00310113
00010193
00208463
FF5FF06F
00000113
0000006F

Seems to not update x2, x3

**Comment by jarmeister99** [comment]
0 - 00F00093 li x1, 15
4 - 00300113 li x2, 3
8 - 00310113 loop: addi x2, x2, 3
C - 00010193 mv x3, x2
10 - 00208463 BEQ x1, x2, done
14 - FF5FF06F j loop
18 - 00010013 done: mv x0, x2
1C - 0000006F d: j d

**Comment by jarmeister99** [comment]
Fixed
